### ISSUE TITLE
Not recognizing plex

### ISSUE THREAD

**Issue by matthewdias** [Atelier-Shiori/hachidori#12]
when playing from plex in chrome, the status window is blank. tested with both the `app.plex.tv/web` url, as well as directly through my server's domain.

also when i click `Update Now`, when the show hasn't been recognized yet, the app crashes with no error message.

**Comment by chikorita157** [comment]
Seems to work fine here. Make sure you are not using a Plex Agent to load meta data or the detection will not work. Using the Plex Agent to load metadata without the episode number will break it. Also, improper matches can also cause issues.

Also, this can be accomplished by changing the folder that contains the anime video files to personal media in the advanced section. This will prevent this issue.

![2017-03-16_00-41-00](https://cloud.githubusercontent.com/assets/161183/23982047/3d5437e0-09e1-11e7-8141-a6906e46e2f0.png)

**Comment by matthewdias** [comment]
hmm, might be another issue. it doesn't work with IINA either. (I use the default Plex Agent too.)

**Comment by chikorita157** [comment]
IINA support has been added in Beta 3, which haven't been released yet.

**Comment by matthewdias** [comment]
ah okay. works with mpv. must be an issue with plex detection after all. any steps to debug?

**Comment by chikorita157** [comment]
You can run the detectstream executable in Hachidori. Do this by right clicking on the Hachidori App > View Package Contents. Click on the resources folder and run the detectstream executable. Copy the terminal output and paste it here.

Also, the page title of the video file being viewed in Plex will help too.

**Comment by matthewdias** [comment]
detectstream picks it up fine:
`{"result":[{"title":"KonoSuba - God's Blessing on This Wonderful World!! -  ·"}]}`

title: `▶ KonoSuba - God's Blessing on This Wonderful World!! - S2 · E10`

crashes on `Update Now`

**Comment by chikorita157** [comment]
It seems that the phrasing is broke. I will just return the title for Plex only and have Anitomy do rest of the phrasing. This should in theory resolve the issues.

**Comment by chikorita157** [comment]
I think I fixed it with https://github.com/Atelier-Shiori/hachidori/commit/d5378fecd53c2f477efdd21c855c1adb63266c00
![2017-03-16_15-03-39](https://cloud.githubusercontent.com/assets/161183/24014121/13ff4316-0a5a-11e7-9835-db9a0a971b2f.png)

Detectstream in theory will only return "KonoSuba - God's Blessing on This Wonderful World!! - S2 · E10" and Anitomy should phrase the rest of the data from the file name so an update can be done properly.

Attached is a test build. This build is sign with a Mac Developer certificate and is only for testing purposes. A new beta build should be out next week, which will be Developer ID signed.
[Hachidori-2.0b2.4-test.zip](https://github.com/Atelier-Shiori/hachidori/files/848769/Hachidori-2.0b2.4-test.zip)
