### ISSUE TITLE
Wrong date on complete

### ISSUE THREAD

**Issue by TopoR** [Atelier-Shiori/hachidori#19]
With AniList as a service, when anime is completed «Finish Date» sets to tomorrow. Time Zones bug maybe? 
Kitsu sets the correct date.

**Comment by moyitpro** [comment]
It might be UTC they are using as there is no option for timezones on AniList. I will ask Josh about this to be sure.

**Comment by moyitpro** [comment]
I want to make sure, the current stable release does not set dates, unless you compiled the latest commit. I will check with Josh about the timezone issue.

**Comment by TopoR** [comment]
Alpha 6 (20180620) not sets dates? Hm... Then it's on the AniList side when the status changes?

**Comment by moyitpro** [comment]
Most likely. Automatic date setting is slated for Alpha 7. I will close this for now.
