### ISSUE TITLE
Plex Media Server secure connections not supported

### ISSUE THREAD

**Issue by ikornaselur** [Atelier-Shiori/hachidori#22]
Plex Media Server has an option to require secure connections in Settings -> Server -> Network:

![image](https://user-images.githubusercontent.com/3537289/44219352-c2419d80-a1b6-11e8-8849-28bbe6be7203.png)

When this setting is on "required", hachidori fails to detect anything playing on the server. Reverting back to "preferred" fixes the issue. 

When set to "required" the following message pops up in the plex media server log when hachidori tries to connect.

```
DEBUG - Request: [x.x.x.x:62001] rejected because secure connections are required
```

**Comment by moyitpro** [comment]
Fixed with:
https://github.com/Atelier-Shiori/hachidori/commit/89beb91894ec08106b7f47ef368257b7a9f9ff7e
https://github.com/Atelier-Shiori/DetectionKit/commit/1f269b14a141edeb9ff431b29f48edb040d7e487
