### ISSUE TITLE
Scrobble/Search issue

### ISSUE THREAD

**Issue by SnipersLaww** [Atelier-Shiori/hachidori#24]
I just updated my OS to Mojave from Yosemite yesterday and updated Hachidori finally to the latest version.  Trying to watch Hinamatsuri and these are what pop up for it. [https://puu.sh/CrBSO/bc7882e209.png](url)(was going to take a screenshot showing it scrobbling it as a Detective Conan movie but that isnt popping up anymore) and this is the filename it is under [https://puu.sh/CrC2w/852a1dbecb.png](url)

**Comment by moyitpro** [comment]
I have tested that file and I cannot reproduce the issue as the title detects properly on Mojave.

You can try clearing out the settings if this resolves the issue.
1. Run the following command in the terminal window to delete the preferences.
defaults delete "moe.ateliershiori.Hachidori"

2. Delete or rename the Hachidori folder in the Application Support folder in the terminal
cd /Users/(Username)/Library/Application Support/

Move the directory temporarily
mv Hachidori Hachidori-bak 

and try again. If you experience the same issues, right click the Hachidori application. Go to the Coontents folder and then MacOS. Run the Hachidori executable. A terminal window will appear. Attempt to do a scrobble and then copy the terminal output to this issue.

**Comment by SnipersLaww** [comment]
2019-01-04 13:31:38.123 Hachidori[27054:1385958] Auto Scrobble Started.
2019-01-04 13:36:38.132 Hachidori[27054:1390145] Starting...
2019-01-04 13:36:38.456 Hachidori[27054:1390145] Debug: .plist-cache.Rq3uqhRm
2019-01-04 13:36:38.476 Hachidori[27054:1390145] Check Exceptions List
2019-01-04 13:36:38.495 Hachidori[27054:1390145] Checking Auto Exceptions
2019-01-04 13:36:38.507 Hachidori[27054:1390145] Checking Auto Exceptions
2019-01-04 13:36:38.507 Hachidori[27054:1390145] =============
2019-01-04 13:36:38.507 Hachidori[27054:1390145] Scrobbling...
2019-01-04 13:36:38.507 Hachidori[27054:1390145] Getting AniID
2019-01-04 13:36:38.521 Hachidori[27054:1390145] Searching For Title
2019-01-04 13:36:39.357 Hachidori[27054:1390145] Title is a movie
2019-01-04 13:36:39.357 Hachidori[27054:1390145] Searching For Title
2019-01-04 13:36:39.580 Hachidori[27054:1390145] Title is a movie
2019-01-04 13:36:39.580 Hachidori[27054:1390145] Searching For Title
2019-01-04 13:36:39.796 Hachidori[27054:1390145] Title is a movie
2019-01-04 13:36:39.796 Hachidori[27054:1390145] Error: Couldn't find title plist-cache RquqhRm. Please add an Anime Exception rule.
2019-01-04 13:36:39.796 Hachidori[27054:1390145] Scrobble Complete with Status Code: 51
2019-01-04 13:36:39.796 Hachidori[27054:1390145] =============
2019-01-04 13:36:39.796 Hachidori[27054:1385958] Auto Scrobble Stopped.

**Comment by moyitpro** [comment]
Can you tell me what video player you are using.

**Comment by SnipersLaww** [comment]
MPlayerX

**Comment by SnipersLaww** [comment]
Detection and everything worked fine back when I was on Yosemite and using an older version of Hachidori.  Update to Mojave and update Hachidori and it hasnt been working since.

**Comment by moyitpro** [comment]
I tried using the copy of MplayerX on Mojave and it detected properly.

Can you try a different video player and see if you having the same issue? I have tested IINA and it works properly.

**Comment by SnipersLaww** [comment]
Tried IINA aswell and still the same thing

**Comment by moyitpro** [comment]
With a video file open, run this command in the terminal.

/usr/sbin/lsof -c IINA -Fn

and copy the output. I need to adjust the regular expression used to retrieve the video file name.

**Comment by SnipersLaww** [comment]
I just redid all the first steps again and had the log up this time (this is before seeing your most recent reply.. so ill update this in a moment after i run your updated comment) and it rescrobbled the detective conan bit again [https://puu.sh/CrEyY/47f7bbb4ec.png](url)
2019-01-04 15:12:50.340 Hachidori[28224:1506638] [Crashlytics] Version 3.10.5 (130)
2019-01-04 15:12:50.405 Hachidori[28224:1506638] -- <__NSObserver: 0x7fe05dc22f10>
2019-01-04 15:12:51.029 Hachidori[28224:1506638] Kitsu is reachable.
2019-01-04 15:12:51.029 Hachidori[28224:1506638] Kitsu is reachable.
2019-01-04 15:13:20.858 Hachidori[28224:1506713] Starting...
2019-01-04 15:13:21.294 Hachidori[28224:1506713] Updating Auto Exceptions!
2019-01-04 15:13:22.313 Hachidori[28224:1506713] Updating Anime Relations!
2019-01-04 15:13:22.866 Hachidori[28224:1506713] Debug: .plist-cache.Rq3uqhRm
2019-01-04 15:13:22.867 Hachidori[28224:1506713] Check Exceptions List
2019-01-04 15:13:22.867 Hachidori[28224:1506713] Checking Auto Exceptions
2019-01-04 15:13:22.867 Hachidori[28224:1506713] Checking Auto Exceptions
2019-01-04 15:13:22.868 Hachidori[28224:1506713] =============
2019-01-04 15:13:22.868 Hachidori[28224:1506713] Scrobbling...
2019-01-04 15:13:22.868 Hachidori[28224:1506713] Getting AniID
2019-01-04 15:13:22.868 Hachidori[28224:1506713] Searching For Title
2019-01-04 15:13:24.234 Hachidori[28224:1506713] Title is a movie
2019-01-04 15:13:24.234 Hachidori[28224:1506713] Valid Episode Count
2019-01-04 15:13:24.236 Hachidori[28224:1506713] Found 698
2019-01-04 15:13:24.236 Hachidori[28224:1506713] Checking 698
2019-01-04 15:13:24.480 Hachidori[28224:1506713] Title on list
2019-01-04 15:13:24.480 Hachidori[28224:1506713] Getting Additional Info
2019-01-04 15:13:24.832 Hachidori[28224:1506713] Updating Title
2019-01-04 15:13:25.006 Hachidori[28224:1506713] Scrobble Complete with Status Code: 22
2019-01-04 15:13:25.006 Hachidori[28224:1506713] =============

(update with your most recent post)
p28286
fcwd
n/
ftxt
n/Applications/IINA.app/Contents/MacOS/IINA
ftxt
n/Applications/IINA.app/Contents/Frameworks/Gzip.framework/Versions/A/Gzip
ftxt
n/Applications/IINA.app/Contents/Frameworks/Just.framework/Versions/A/Just
ftxt
n/Applications/IINA.app/Contents/Frameworks/Mustache.framework/Versions/A/Mustache
ftxt
n/Applications/IINA.app/Contents/Frameworks/PromiseKit.framework/Versions/A/PromiseKit
ftxt
n/Applications/IINA.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
ftxt
n/Applications/IINA.app/Contents/Frameworks/libvorbisenc.2.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libpcre.1.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libavformat.58.20.100.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libarchive.13.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libgraphite2.3.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libSDL2-2.0.0.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libglib-2.0.0.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libmpv.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libdvdcss.2.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libfreetype.6.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/liblua.5.1.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libopus.0.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libjpeg.9.dylib
ftxt
n/Library/Preferences/Logging/.plist-cache.Rq3uqhRm
ftxt
n/Applications/IINA.app/Contents/Frameworks/libtheoradec.1.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswscale.5.3.100.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libdvdnav.4.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libass.9.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libvorbis.0.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libdvdread.4.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libfontconfig.1.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libtheoraenc.1.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libavresample.4.0.0.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/liblzma.5.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libavutil.56.22.100.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libbluray.2.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libpng16.16.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libavdevice.58.5.100.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libsnappy.1.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libharfbuzz.0.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libpostproc.55.3.100.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libavfilter.7.40.101.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libmp3lame.0.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/liblcms2.2.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libintl.8.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libfribidi.0.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libavcodec.58.35.100.dylib
ftxt
n/usr/lib/libobjc-trampolines.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libuchardet.0.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libogg.0.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswresample.3.3.100.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftAVFoundation.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftAppKit.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftCore.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftCoreAudio.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftCoreData.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftCoreFoundation.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftCoreGraphics.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftCoreImage.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftCoreMedia.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftDarwin.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftDispatch.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftFoundation.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftIOKit.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftMetal.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftObjectiveC.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftQuartzCore.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftXPC.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftsimd.dylib
ftxt
n/Applications/IINA.app/Contents/Frameworks/libswiftos.dylib
ftxt
n/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car
ftxt
n/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAquaAppearance.car
ftxt
n/usr/lib/dyld
ftxt
n/usr/share/icu/icudt62l.dat
ftxt
n/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAppearance.car
ftxt
n/System/Library/Fonts/SFNSText.ttf
ftxt
n/private/var/folders/wx/38vzrz2j4gb02wv40601xffc0000gn/0/com.apple.LaunchServices-231-v2.csstore
ftxt
n/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car
ftxt
n/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
ftxt
n/private/var/folders/wx/38vzrz2j4gb02wv40601xffc0000gn/C/com.colliderli.iina/com.apple.metal/3902/libraries.data
ftxt
n/private/var/folders/wx/38vzrz2j4gb02wv40601xffc0000gn/C/com.colliderli.iina/com.apple.metal/Intel Iris Graphics/functions.data
ftxt
n/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLightAppearance.car
ftxt
n/System/Library/Caches/com.apple.IntlDataCache.le.kbdx
ftxt
n/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat
ftxt
n/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/Assets.car
ftxt
n/System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn
ftxt
n/Library/MessageTracer/SubmitDiagInfo.default.domains.searchtree
ftxt
n/Library/Caches/com.apple.iconservices.store/18292B4E-845C-C826-64A9-D95AA3E89379.isdata
ftxt
n/Applications/IINA.app/Contents/Resources/Assets.car
ftxt
n/private/var/folders/wx/38vzrz2j4gb02wv40601xffc0000gn/C/com.apple.iconservices/store.index
ftxt
n/System/Library/Fonts/SFNSDisplay.ttf
ftxt
n/private/var/db/mds/messages/501/se_SecurityMessages
ftxt
n/private/var/db/nsurlstoraged/dafsaData.bin
ftxt
n/System/Library/Extensions/AppleIntelHD5000GraphicsVADriver.bundle/Contents/MacOS/AppleIntelHD5000GraphicsVADriver
ftxt
n/System/Library/Extensions/AppleIntelHSWVA.bundle/Contents/MacOS/AppleIntelHSWVA
ftxt
n/System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio
f0
n/dev/null
f1
n/dev/null
f2
n/dev/null
f3
n/Users/<user>/Library/Logs/com.colliderli.iina/2019-01-04-15-17-46_fOdPeW/iina.log
f4
n->0xeb898cb931e2a937
f5
n->0xeb898cb914ef503f
f6
n/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_stdlib.metallib
f7
n/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_filters.metallib
f8
n/private/var/folders/wx/38vzrz2j4gb02wv40601xffc0000gn/C/com.colliderli.iina/com.apple.metal/3902/libraries.maps
f9
n/private/var/folders/wx/38vzrz2j4gb02wv40601xffc0000gn/C/com.colliderli.iina/com.apple.metal/3902/libraries.data
f10
n/private/var/folders/wx/38vzrz2j4gb02wv40601xffc0000gn/C/com.colliderli.iina/com.apple.metal/Intel Iris Graphics/functions.maps
f11
n/private/var/folders/wx/38vzrz2j4gb02wv40601xffc0000gn/C/com.colliderli.iina/com.apple.metal/Intel Iris Graphics/functions.data
f12
n->0xeb898cb931e2a3f7
f13
n/Library/MessageTracer/SubmitDiagInfo.default.domains.searchtree
f14
n->0xeb898cb931e2b0b7
f15
n->0xeb898cb931e2c4f7
f16
n/Users/<user>/Public/[HorribleSubs] Black Clover - 62 [720p].mkv
f17
n/Users/<user>/Library/Caches/com.colliderli.iina/Cache.db
f18
n/Users/<user>/Library/Saved Application State/com.colliderli.iina.savedState/window_1.data
f19
nFNetwork.defaultStorageSession
f20
n
f21
n10.0.0.2:60079->104.18.55.224:https
f22
n/Users/<user>/Library/Saved Application State/com.colliderli.iina.savedState/data.data
f23
n[ctl com.apple.netsrc id 8 unit 16]
f24
n/private/var/db/nsurlstoraged/dafsaData.bin
f25
n/Users/<user>/Library/Saved Application State/com.colliderli.iina.savedState/windows.plist

(I replaced my username with <user> in the paste)

**Comment by SnipersLaww** [comment]
okay.. apparently carrots got removed.. but i replaced my username in the post.. so ignore the space where there should be a username >_>

**Comment by moyitpro** [comment]
Figured out the issue. The regular expressions used to retrieve the open file is causing the ".plist-cache.Rq3uqhRm" to be detected ambiguously as a real media file when it's not an actual video file. I used your output in the test program used to test the media file detection and it appears to work.

{
    detectedepisode = 62;
    detectedseason = 1;
    detectedsource = mpv;
    detectedtitle = "Black Clover";
    group = HorribleSubs;
    types =     (
    );
}

Fix: https://github.com/Atelier-Shiori/DetectionKit/commit/f763752965016efe176ab255edc334f02e689bcb

**Comment by SnipersLaww** [comment]
sure.. its not like the current build is working for me >_>
just let me know what i need to do

**Comment by moyitpro** [comment]
[hachidori-3.0.9.dmg.zip](https://github.com/Atelier-Shiori/hachidori/files/2728640/hachidori-3.0.9.dmg.zip)

Just test a scrobble normally and let me know the results.

**Comment by SnipersLaww** [comment]
first run is a success
