### ISSUE TITLE
Stuck at «Updating...»

### ISSUE THREAD

**Issue by TopoR** [Atelier-Shiori/hachidori#39]
Since today-yesterday Hachidori 3.2b4 has stopped to scrobble at any service. Just stuck at the «Updating...» line.

**Comment by moyitpro** [comment]
Can you provide a copy of the log. This is located under ~/Library/Application Support/Hachidori. 

Also provide what title you are trying to update.

**Comment by TopoR** [comment]
Oh, thanks for the Log tip. Yeah, there was a Kitsu token error spam which was preventing scrobbling.

**Comment by moyitpro** [comment]
I will take a look at the token refresh issues probably sometime next week. You can fix this by reauthorizing your Kitsu account for the time being.

**Comment by TopoR** [comment]
Yeah, thanks. I disabled Kitsu, since this was not the main anime list for me. It turned out that Kitsu IP was blocked in my country, which, I think, was the main problem.

**Comment by moyitpro** [comment]
Ok, thanks for letting me know. I will close this issue if Kitsu is actually blocked in your country.
