### ISSUE TITLE
Attack on Titan - Anime Title Exceptions 

### ISSUE THREAD

**Issue by oneshotoli** [Atelier-Shiori/hachidori#43]
So Attack on Titan has 4 seasons and when I open season 2, 3, or 4 to any episode it will not recognize and the pop-up adds anime title exception rule box will show. However, nothing appears in the box and I manually type in "attack on titan" and add the continuous seasons. What would I need to change in offset and threshold for it to recognize and autoscrobble properly?

**Comment by moyitpro** [comment]
Can you provide where you are watching this series and what list service. Also upload the scrobble log, which can be accessed from the preferences

Sent from my iPhone 11 Pro
(Shijou Takane - 四条貴音)

**Comment by oneshotoli** [comment]
I'm watching the series on Crunchyroll. The list service I use is Anilist. I've attached my scrobble log.
I also want to mention I did reauthorize my account for anilist. 
[Hachidori.log](https://github.com/Atelier-Shiori/hachidori/files/6174332/Hachidori.log)

**Comment by moyitpro** [comment]
It appeared that the Anime Relations feature wasn't implemented properly. I pushed a new fix and 3.3.3-beta2 will fix this.

https://github.com/Atelier-Shiori/hachidori/commit/e88fd282af251e8c42baa7c36011ba0a6ae54c6c

![Screen Shot 2021-03-20 at 10 22 26 AM](https://user-images.githubusercontent.com/161183/111873342-40b1dd80-8966-11eb-9d21-cda5a6712cd8.png)

**Comment by moyitpro** [comment]
The build that fixes this issue is now uploaded.

https://github.com/Atelier-Shiori/hachidori/releases/tag/3.3.3-beta2
