### ISSUE TITLE
Anime title correction doesn't work in some case

### ISSUE THREAD

**Issue by beam2546** [Atelier-Shiori/hachidori#46]
Video: https://files.catbox.moe/4agala.mov

Reproduce: Open an anime file that need to correct the title then scrobble it by either manually or automatically, correct the title name then close the file. Reopen it and scrobble it again. Old title before correction will still be use in some case instead of corrected title.

Log: [Hachidori.log](https://github.com/Atelier-Shiori/hachidori/files/7190366/Hachidori.log)

**Comment by moyitpro** [comment]
I tried correcting a title in my end and it seems to work. I think it may have to do with the file name being problematic. Can I have the file names for the video files you having trouble with?

**Comment by beam2546** [comment]
File name: New Game! (2016) - S02E03 - 016 - Ooh Im So Embarrassed! [Bluray-1080p][10bit][x264][FLAC 5.1]-[NH]

Format on Sonarr: {Series TitleYear} - S{season:00}E{episode:00} - {absolute:000} - {Episode CleanTitle} [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRange]}[{MediaInfo VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{-[Release Group]}

Seem like file name is a problem. I changed it to original file name ([NH] New Game!! S2 - 03 (BD 1080p x264 10-bit FLAC) [E5408181]) and it seem to be fine after correction.

**Comment by moyitpro** [comment]
This is how Anitomy parsed the file name, but nothing too out of the ordinary.

> {
>     episode = 03;
>     episodetitle = "016 - Ooh Im So Embarrassed!";
>     episodetype = "";
>     filechecksum = "";
>     filename = "New Game! (2016) - S02E03 - 016 - Ooh Im So Embarrassed! [Bluray-1080p][10bit][x264][FLAC 5.1]-[NH]";
>     filetype = mkv;
>     group = NH;
>     language = "";
>     releaseinfo = "";
>     releaseversion = "";
>     season = 02;
>     subtitles = "";
>     title = "New Game!";
>     type =     (
>     );
>     videoresolution = 1080p;
>     videosource = Bluray;
>     videoterm = 10bit;
>     volumenum = "";
>     volumeprefix = "";
>     year = 2016;
> }

I will look more into it when I have the chance.

**Comment by moyitpro** [comment]
I pushed a commit that fixed this issue. This title now detects properly after adding support for spelled out oridnal numbers as some alternate titles used a spelled out ordinal title (e.g. second season) to number its season.

Debug output:
```
DEBUG                           -[AppDelegate firetimer]:887 - [9/19/21 1:43 PM] Starting...
2021-09-19 13:43:45.922301-0400 Hachidori[83440:8249649] Debug: New Game! (2016) - S02E03 - 016 - Ooh Im So Embarrassed! [Bluray-1080p][10bit][x264][FLAC 5.1]-[NH].MP4
DEBUG                       -[Hachidori checkExceptions]:646 - [9/19/21 1:43 PM] Check Exceptions List
DEBUG                       -[Hachidori checkExceptions]:656 - [9/19/21 1:43 PM] Checking Auto Exceptions
DEBUG                       -[Hachidori checkExceptions]:656 - [9/19/21 1:43 PM] Checking Auto Exceptions
DEBUG                              -[Hachidori scrobble]:441 - [9/19/21 1:43 PM] =============
DEBUG                              -[Hachidori scrobble]:442 - [9/19/21 1:43 PM] Scrobbling...
DEBUG                              -[Hachidori scrobble]:443 - [9/19/21 1:43 PM] Check Account Information
DEBUG                              -[Hachidori scrobble]:445 - [9/19/21 1:43 PM] Getting AniID
DEBUG                -[Hachidori(Search) performSearch:]: 49 - [9/19/21 1:43 PM] Searching For Title
2021-09-19 13:43:46.266270-0400 Hachidori[83440:8249643] [connection] nw_endpoint_handler_set_adaptive_read_handler [C3.1 65.8.67.80:443 ready socket-flow (satisfied (Path is satisfied), viable, interface: ipsec0, ipv4, dns, flow divert agg: 1)] unregister notification for read_timeout failed
2021-09-19 13:43:46.266326-0400 Hachidori[83440:8249643] [connection] nw_endpoint_handler_set_adaptive_write_handler [C3.1 65.8.67.80:443 ready socket-flow (satisfied (Path is satisfied), viable, interface: ipsec0, ipv4, dns, flow divert agg: 1)] unregister notification for write_timeout failed
DEBUG         -[Hachidori(Search) findaniid:searchterm:]:111 - [9/19/21 1:45 PM] Title is not a movie.
DEBUG         -[Hachidori(Search) findaniid:searchterm:]:160 - [9/19/21 1:46 PM] Valid Episode Count
DEBUG                              -[Hachidori scrobble]:464 - [9/19/21 1:46 PM] Found 34914
DEBUG  -[Hachidori(UserStatus) checkstatus:withService:]: 18 - [9/19/21 1:46 PM] Checking 34914
2021-09-19 13:46:08.811356-0400 Hachidori[83440:8250649] [connection] nw_endpoint_handler_set_adaptive_read_handler [C4.1 143.204.47.102:443 ready socket-flow (satisfied (Path is satisfied), viable, interface: ipsec0, ipv4, dns, flow divert agg: 1)] unregister notification for read_timeout failed
2021-09-19 13:46:08.811411-0400 Hachidori[83440:8250649] [connection] nw_endpoint_handler_set_adaptive_write_handler [C4.1 143.204.47.102:443 ready socket-flow (satisfied (Path is satisfied), viable, interface: ipsec0, ipv4, dns, flow divert agg: 1)] unregister notification for write_timeout failed
DEBUG  -[Hachidori(UserStatus) checkstatus:withService:]: 65 - [9/19/21 1:46 PM] Title on list
DEBUG -[Hachidori(UserStatus) retrieveAnimeInfo:withService:]:124 - [9/19/21 1:46 PM] Getting Additional Info
DEBUG                  -[Hachidori(Update) updatetitle:]: 26 - [9/19/21 1:46 PM] Updating Title
DEBUG                              -[Hachidori scrobble]:521 - [9/19/21 1:46 PM] Scrobble Complete with Status Code: 2 - Update is not needed.
DEBUG                              -[Hachidori scrobble]:522 - [9/19/21 1:46 PM]
```
Which points to New Game!! on MyAnimeList and not the first season. I will release this fix in the near future.
https://myanimelist.net/anime/34914

**Comment by moyitpro** [comment]
Fixed with https://github.com/Atelier-Shiori/hachidori/commit/df2835e2432244c49243dff2353a75d9ae0f3493
